In [1]:
import vtk
from vtk.numpy_interface import dataset_adapter as dsa
from vmtk import vmtkscripts
import numpy as np

import os

In [2]:
datadir = '/Users/rick/projects/vmtk/vmtk-test-data/input/'

In [3]:
centerlinereader = vmtkscripts.vmtkSurfaceReader()
centerlinereader.InputFileName = os.path.join(datadir, 'aorta-centerline-branches.vtp')
centerlinereader.Execute()

Reading VTK XML surface file.


In [4]:
bifur = vmtkscripts.vmtkBifurcationReferenceSystems()
bifur.Centerlines = centerlinereader.Surface
bifur.RadiusArrayName = 'MaximumInscribedSphereRadius'
bifur.BlankingArrayName = 'Blanking'
bifur.GroupIdsArrayName = 'GroupIds'
bifur.Execute()

In [5]:
ref = bifur.ReferenceSystems

In [9]:
dataArrays = ref.GetPointData()

In [10]:
dataArrays.GetNumberOfArrays()

3

In [11]:
dataArrays.GetArrayName(0)

'Normal'

In [17]:
array = dataArrays.GetArray(0)
array.GetNumberOfComponents()

3

In [12]:
dataArrays.GetArrayName(1)

'UpNormal'

In [18]:
array = dataArrays.GetArray(1)
array.GetNumberOfComponents()

3

In [13]:
dataArrays.GetArrayName(2)

'GroupIds'

In [19]:
array = dataArrays.GetArray(2)
array.GetNumberOfComponents()

1

In [20]:
ref.GetNumberOfPoints()

1

In [21]:
ref.GetPoint(0)

(221.66326904296875, 138.3250732421875, 24.043575286865234)

In [32]:
array = dataArrays.GetArray('Normal')

np.array([array.GetComponent(0, 0), array.GetComponent(0, 1), array.GetComponent(0, 2)])

array([-0.16795282, -0.05915027, -0.98401885])

In [28]:
array = dataArrays.GetArray('UpNormal')

In [29]:
np.array([array.GetComponent(0, 0), array.GetComponent(0, 1), array.GetComponent(0, 2)])

array([-0.00365111, -0.99815405,  0.06062313])

In [30]:
array = dataArrays.GetArray('GroupIds')

In [31]:
np.array([array.GetComponent(0, 0)])

array([ 1.])

In [6]:
print(ref)

vtkPolyData (0x7febeaa7d820)
  Debug: Off
  Modified Time: 689
  Reference Count: 1
  Registered Events: (none)
  Information: 0x7febeaa7d990
  Data Released: False
  Global Release Data: Off
  UpdateTime: 696
  Field Data:
    Debug: Off
    Modified Time: 679
    Reference Count: 1
    Registered Events: (none)
    Number Of Arrays: 0
    Number Of Components: 0
    Number Of Tuples: 0
  Number Of Points: 0
  Number Of Cells: 0
  Cell Data:
    Debug: Off
    Modified Time: 687
    Reference Count: 1
    Registered Events: 
      Registered Observers:
        vtkObserver (0x7febeaa7d360)
          Event: 33
          EventName: ModifiedEvent
          Command: 0x7febeaa7d2c0
          Priority: 0
          Tag: 1
    Number Of Arrays: 0
    Number Of Components: 0
    Number Of Tuples: 0
    Copy Tuple Flags: ( 1 1 1 1 1 0 1 1 )
    Interpolate Flags: ( 1 1 1 1 1 0 0 1 )
    Pass Through Flags: ( 1 1 1 1 1 1 1 1 )
    Scalars: (none)
    Vectors: (none)
    Normals: (none)
    TCoord

In [11]:
clipsurf = branchclipper.Surface

In [13]:
wpclipsurf = dsa.WrapDataObject(clipsurf)

In [21]:
wpclipsurf.PointData['GroupIds'].shape

(6826,)

In [12]:
print(clipsurf)

vtkPolyData (0x7fbf0ed3adb0)
  Debug: Off
  Modified Time: 423791
  Reference Count: 3
  Registered Events: (none)
  Information: 0x7fbf0ed3af20
  Data Released: False
  Global Release Data: Off
  UpdateTime: 424398
  Field Data:
    Debug: Off
    Modified Time: 422160
    Reference Count: 1
    Registered Events: (none)
    Number Of Arrays: 0
    Number Of Components: 0
    Number Of Tuples: 0
  Number Of Points: 6826
  Number Of Cells: 13288
  Cell Data:
    Debug: Off
    Modified Time: 422103
    Reference Count: 1
    Registered Events: 
      Registered Observers:
        vtkObserver (0x7fbf0ed3b470)
          Event: 33
          EventName: ModifiedEvent
          Command: 0x7fbf0ed3b1a0
          Priority: 0
          Tag: 1
    Number Of Arrays: 0
    Number Of Components: 0
    Number Of Tuples: 0
    Copy Tuple Flags: ( 1 1 1 1 1 0 1 1 )
    Interpolate Flags: ( 1 1 1 1 1 0 0 1 )
    Pass Through Flags: ( 1 1 1 1 1 1 1 1 )
    Scalars: (none)
    Vectors: (none)
    Normals

In [6]:
surfaceviewer = vmtkscripts.vmtkSurfaceViewer()
surfaceviewer.Surface = branchclipper.Surface
surfaceviewer.ArrayName = 'GroupIds'
surfaceviewer.Execute()

Quit renderer


In [ ]:
centerlineviewer = vmtkscripts.vmtkCenterlineViewer()
centerlineviewer.Centerlines = branchgeometry.Centerlines
centerlineviewer.Execute()