In [1]:
import vtk
from vtk.numpy_interface import dataset_adapter as dsa
from vmtk import vmtkscripts
import numpy as np

import os

In [2]:
datadir = '/Users/rick/projects/vmtk/vmtk-test-data/input/'

In [3]:
centerlinereader = vmtkscripts.vmtkSurfaceReader()
centerlinereader.InputFileName = os.path.join(datadir, 'aorta-centerline-branches.vtp')
centerlinereader.Execute()

Reading VTK XML surface file.


In [4]:
surfacereader = vmtkscripts.vmtkSurfaceReader()
surfacereader.InputFileName = os.path.join(datadir, 'aorta-surface-branch-split.vtp')
surfacereader.Execute()

Reading VTK XML surface file.


In [6]:
profiles = vmtkscripts.vmtkBifurcationProfiles()
profiles.Surface = surfacereader.Surface
profiles.Centerlines = centerlinereader.Surface
profiles.RadiusArrayName = 'MaximumInscribedSphereRadius'
profiles.GroupIdsArrayName = 'GroupIds'
profiles.CenterlineIdsArrayName = 'CenterlineIds'
profiles.TractIdsArrayName = 'TractIds'
profiles.BlankingArrayName = 'Blanking'

profiles.Execute()

In [7]:
bifurs = profiles.BifurcationProfiles

In [8]:
wp = dsa.WrapDataObject(bifurs)

In [9]:
wp.CellData.keys()

['BifurcationProfileGroupIds',
 'BifurcationProfileBifurcationGroupIds',
 'BifurcationProfileOrientation']

In [12]:
cellDataKeys = ['BifurcationProfileGroupIds',
                 'BifurcationProfileBifurcationGroupIds',
                 'BifurcationProfileOrientation']

In [13]:
objectCellDataKeys = wp.CellData.keys()
for cellKey in cellDataKeys:
    assert cellKey in objectCellDataKeys
    objectCellDataKeys.remove(cellKey)
    
assert len(objectCellDataKeys) == 0

In [14]:
assert len(wp.PointData.keys()) == 0

In [15]:
for key in cellDataKeys:
    print(f'{key} \n {wp.CellData.GetArray(key)}')

BifurcationProfileGroupIds 
 [0 2 3]
BifurcationProfileBifurcationGroupIds 
 [1 1 1]
BifurcationProfileOrientation 
 [0 1 1]


In [18]:
print(bifurs)

vtkPolyData (0x7f8bd216d940)
  Debug: Off
  Modified Time: 1447
  Reference Count: 1
  Registered Events: (none)
  Information: 0x7f8bd216dab0
  Data Released: False
  Global Release Data: Off
  UpdateTime: 3490
  Field Data:
    Debug: Off
    Modified Time: 1383
    Reference Count: 1
    Registered Events: (none)
    Number Of Arrays: 0
    Number Of Components: 0
    Number Of Tuples: 0
  Number Of Points: 358
  Number Of Cells: 3
  Cell Data:
    Debug: Off
    Modified Time: 1428
    Reference Count: 1
    Registered Events: 
      Registered Observers:
        vtkObserver (0x7f8bd2171330)
          Event: 33
          EventName: ModifiedEvent
          Command: 0x7f8bd216cab0
          Priority: 0
          Tag: 1
    Number Of Arrays: 3
    Array 0 name = BifurcationProfileGroupIds
    Array 1 name = BifurcationProfileBifurcationGroupIds
    Array 2 name = BifurcationProfileOrientation
    Number Of Components: 3
    Number Of Tuples: 3
    Copy Tuple Flags: ( 1 1 1 1 1 0 1 1 )

In [21]:
for idx in range(3):
    print(f'For cell: {idx}')
    bcx = bifurs.GetCell(idx)
    numberOfPoints = bcx.GetNumberOfPoints()
    pointIdStart = bcx.GetPointId(0)
    pointIdEnd = bcx.GetPointId(numberOfPoints - 1)
    pointLocationStart = wp.Points[pointIdStart]
    pointLocationEnd = wp.Points[pointIdEnd]
    print(f'Number Of Points: {numberOfPoints} \n',
          f'Point Id Start: {pointIdStart} \n',
          f'Point Id End: {pointIdEnd} \n',
          f'Point Location Start: {pointLocationStart} \n',
          f'Point Location End: {pointLocationEnd} \n')

For cell: 0
Number Of Points: 132 
 Point Id Start: 0 
 Point Id End: 131 
 Point Location Start: [ 221.89123535  135.91229248   17.98954964] 
 Point Location End: [ 221.82603455  135.88433838   18.00107956] 

For cell: 1
Number Of Points: 106 
 Point Id Start: 132 
 Point Id End: 237 
 Point Location Start: [ 222.36294556  136.11395264   17.92448616] 
 Point Location End: [ 222.40290833  136.13102722   17.91927338] 

For cell: 2
Number Of Points: 120 
 Point Id Start: 238 
 Point Id End: 357 
 Point Location Start: [ 221.05075073  132.63262939   19.5011692 ] 
 Point Location End: [ 221.05207825  132.61680603   19.50825119] 



In [20]:
bcx

(vtkCommonDataModelPython.vtkPolyLine)0x11a3f19a8

In [32]:
assert wp.Points.shape == (280, 3)

In [17]:
print(bifurs)

vtkPolyData (0x7f8bd216d940)
  Debug: Off
  Modified Time: 1447
  Reference Count: 1
  Registered Events: (none)
  Information: 0x7f8bd216dab0
  Data Released: False
  Global Release Data: Off
  UpdateTime: 3490
  Field Data:
    Debug: Off
    Modified Time: 1383
    Reference Count: 1
    Registered Events: (none)
    Number Of Arrays: 0
    Number Of Components: 0
    Number Of Tuples: 0
  Number Of Points: 358
  Number Of Cells: 3
  Cell Data:
    Debug: Off
    Modified Time: 1428
    Reference Count: 1
    Registered Events: 
      Registered Observers:
        vtkObserver (0x7f8bd2171330)
          Event: 33
          EventName: ModifiedEvent
          Command: 0x7f8bd216cab0
          Priority: 0
          Tag: 1
    Number Of Arrays: 3
    Array 0 name = BifurcationProfileGroupIds
    Array 1 name = BifurcationProfileBifurcationGroupIds
    Array 2 name = BifurcationProfileOrientation
    Number Of Components: 3
    Number Of Tuples: 3
    Copy Tuple Flags: ( 1 1 1 1 1 0 1 1 )

In [12]:
sections.OutputSectionArea

0.0

In [8]:
surfaceviewer = vmtkscripts.vmtkSurfaceViewer()
surfaceviewer.Surface = sections.Surface
surfaceviewer.ArrayName = 'BifurcationSectionGroupIds'
surfaceviewer.Execute()

Quit renderer
