In [1]:
import vtk
from vtk.numpy_interface import dataset_adapter as dsa
from vmtk import vmtkscripts
import numpy as np

import os

In [2]:
datadir = '/Users/rick/projects/vmtk/vmtk-test-data/input/'

In [3]:
centerlinereader = vmtkscripts.vmtkSurfaceReader()
centerlinereader.InputFileName = os.path.join(datadir, 'aorta-centerline-attribute-branches.vtp')
centerlinereader.Execute()

Reading VTK XML surface file.


In [4]:
surfacereader = vmtkscripts.vmtkSurfaceReader()
surfacereader.InputFileName = os.path.join(datadir, 'aorta-surface-branch-split.vtp')
surfacereader.Execute()

Reading VTK XML surface file.


In [5]:
metrics = vmtkscripts.vmtkBranchMetrics()
metrics.Surface = surfacereader.Surface
metrics.Centerlines = centerlinereader.Surface
metrics.AbscissasArrayName = 'Abscissas'
metrics.NormalsArrayName = 'ParallelTransportNormals'
metrics.RadiusArrayName = 'MaximumInscribedSphereRadius'
metrics.GroupIdsArrayName = 'GroupIds'
metrics.CenterlineIdsArrayName = 'CenterlineIds'
metrics.TractIdsArrayName = 'TractIds'
metrics.BlankingArrayName = 'Blanking'
metrics.Execute()

Computing angular metric
Computing abscissa metric


In [6]:
surf = metrics.Surface

In [7]:
print(surf)

vtkPolyData (0x7fe8e6744e40)
  Debug: Off
  Modified Time: 514237
  Reference Count: 1
  Registered Events: (none)
  Information: 0x7fe8e674f970
  Data Released: False
  Global Release Data: Off
  UpdateTime: 898492
  Field Data:
    Debug: Off
    Modified Time: 514209
    Reference Count: 1
    Registered Events: (none)
    Number Of Arrays: 0
    Number Of Components: 0
    Number Of Tuples: 0
  Number Of Points: 6826
  Number Of Cells: 13288
  Cell Data:
    Debug: Off
    Modified Time: 514140
    Reference Count: 1
    Registered Events: 
      Registered Observers:
        vtkObserver (0x7fe8e674fec0)
          Event: 33
          EventName: ModifiedEvent
          Command: 0x7fe8e674fbf0
          Priority: 0
          Tag: 1
    Number Of Arrays: 0
    Number Of Components: 0
    Number Of Tuples: 0
    Copy Tuple Flags: ( 1 1 1 1 1 0 1 1 )
    Interpolate Flags: ( 1 1 1 1 1 0 0 1 )
    Pass Through Flags: ( 1 1 1 1 1 1 1 1 )
    Scalars: (none)
    Vectors: (none)
    Normals

In [8]:
wp = dsa.WrapDataObject(surf)

In [9]:
wp.PointData.keys()

['Scalars_',
 'GroupIds',
 'ClippingArray',
 'Normals_',
 'AngularMetric',
 'AbscissaMetric']

In [10]:
cellDataKeys = ['Scalars_',
                 'GroupIds',
                 'ClippingArray',
                 'Normals_',
                 'AngularMetric',
                 'AbscissaMetric']

In [13]:
objectCellDataKeys = wp.PointData.keys()
for cellKey in cellDataKeys:
    print(cellKey)
    assert cellKey in objectCellDataKeys
    objectCellDataKeys.remove(cellKey)
    
assert len(objectCellDataKeys) == 0

Scalars_
GroupIds
ClippingArray
Normals_
AngularMetric
AbscissaMetric


In [23]:
assert len(wp.PointData.keys()) == 0

In [16]:
for key in cellDataKeys:
    print(f'{key} \n {wp.PointData.GetArray(key)}')

Scalars_ 
 [ 0.  0.  0. ...,  0.  0.  0.]
GroupIds 
 [0 0 0 ..., 3 3 3]
ClippingArray 
 [ 1483.45955408  1480.89258716  1472.0679105  ...,   506.61756505
   574.64533848   535.71195108]
Normals_ 
 [[ 0.19418415  0.50526708  0.84083158]
 [ 0.24531646  0.54545981  0.80143207]
 [ 0.2298568   0.51062083  0.82851201]
 ..., 
 [-0.33664939 -0.18728521 -0.92281711]
 [ 0.115893   -0.27621996 -0.95408142]
 [-0.08968667 -0.23658742 -0.967462  ]]
AngularMetric 
 [ 1.82336061  1.86045107  1.8287439  ..., -1.06461794 -1.67579795
 -1.42419953]
AbscissaMetric 
 [  3.88414617   3.88414617   3.88414617 ...,  75.28235213  75.28235213
  75.28235213]


In [25]:
wp.Points.shape

(294, 3)

In [26]:
assert wp.Points.shape == (280, 3)

AssertionError: 

In [28]:
for idx in range(3):
    print(f'For cell: {idx}')
    bcx = bifurs.GetCell(idx)
    numberOfPoints = bcx.GetNumberOfPoints()
    pointIdStart = bcx.GetPointId(0)
    pointIdEnd = bcx.GetPointId(numberOfPoints - 1)
    pointLocationStart = wp.Points[pointIdStart]
    pointLocationEnd = wp.Points[pointIdEnd]
    print(f'Number Of Points: {numberOfPoints} \n',
          f'Point Id Start: {pointIdStart} \n',
          f'Point Id End: {pointIdEnd} \n',
          f'np.array({pointLocationStart}), np.array({pointLocationEnd}) \n')

For cell: 0
Number Of Points: 124 
 Point Id Start: 0 
 Point Id End: 123 
 np.array([ 220.9937439   146.86668396   16.48843384]), np.array([ 221.39068604  146.87068176   16.47060013]) 

For cell: 1
Number Of Points: 80 
 Point Id Start: 124 
 Point Id End: 203 
 np.array([ 225.22320557  128.92987061   19.44786835]), np.array([ 225.25431824  128.94456482   19.42810059]) 

For cell: 2
Number Of Points: 90 
 Point Id Start: 204 
 Point Id End: 293 
 np.array([ 221.40382385  128.67816162   22.39156914]), np.array([ 221.80430603  128.64775085   24.46484756]) 



In [14]:
print(bifurs)

vtkPolyData (0x7fa3bf082320)
  Debug: Off
  Modified Time: 1546
  Reference Count: 1
  Registered Events: (none)
  Information: 0x7fa3bf082490
  Data Released: False
  Global Release Data: Off
  UpdateTime: 7982
  Field Data:
    Debug: Off
    Modified Time: 1392
    Reference Count: 1
    Registered Events: (none)
    Number Of Arrays: 0
    Number Of Components: 0
    Number Of Tuples: 0
  Number Of Points: 280
  Number Of Cells: 3
  Cell Data:
    Debug: Off
    Modified Time: 1527
    Reference Count: 1
    Registered Events: 
      Registered Observers:
        vtkObserver (0x7fa3bf062d30)
          Event: 33
          EventName: ModifiedEvent
          Command: 0x7fa3bf070b00
          Priority: 0
          Tag: 1
    Number Of Arrays: 11
    Array 0 name = BifurcationSectionGroupIds
    Array 1 name = BifurcationSectionBifurcationGroupIds
    Array 2 name = BifurcationSectionPoint
    Array 3 name = BifurcationSectionNormal
    Array 4 name = BifurcationSectionArea
    Array 5 

In [ ]:
sections.OutputSectionArea

In [9]:
surfaceviewer = vmtkscripts.vmtkSurfaceViewer()
surfaceviewer.Surface = surf
surfaceviewer.ArrayName = 'AbscissaMetric'
surfaceviewer.Execute()

Quit renderer
